version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs.db:/app/logs.db
    environment:
      - FLASK_ENV=production
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
